#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
github: [metadata]
packages_official:
  -
    name: kernel
    github: micro-kernel
  -
    name: kernel-app
    github: micro-kernel-app
  -
    name: autowire
    github: container-autowire
  -
    name: dependency-injection
    github: lib-dependency-injection
#  -
#    name: deprecation-supports
#    github: deprecation-supports
  -
    name: kernel-boot-configuration
    github: kernel-boot-configuration
  -
    name: kernel-boot-dependency
    github: kernel-boot-dependency
  -
    name: kernel-boot-plugin-depended
    github: kernel-boot-plugin-depended
  -
    name:  plugin-configuration-helper
    github: plugin-configuration-helper
  -
    name:  plugin-http-boot
    github: http-boot
  -
    name:  plugin-http-core
    github: plugin-http-core
  -
    name:  plugin-http-exceptions
    github: http-exceptions
  -
    name:  plugin-http-exceptions-dev
    github: http-exception-dev
  -
    name:  plugin-http-logger
    github: http-logger
  -
    name:  plugin-http-middleware
    github: http-middleware
  -
    name:  plugin-http-pack
    github: http-pack
  -
    name:  plugin-http-router-code
    github: http-router-code
  -
    name:  plugin-locator
    github: plugin-locator
  -
    name:  plugin-logger-core
    github: plugin-logger

  -
    name:  plugin-logger-monolog
    github: plugin-logger-monolog
  -
    name:  plugin-twig
    github: plugin-twig
  -
    name:  plugin-console
    github: plugin-console
  -
    name:  plugin-doctrine
    github: plugin-doctrine
  -
    name:  plugin-dto
    github: plugin-dto
  -
    name:  plugin-elastic
    github: plugin-elastic
  -
    name:  plugin-event-emitter
    github: plugin-event-emitter
  -
    name:  plugin-filesystem
    github: plugin-filesystem
  -
    name:  plugin-filesystem-local
    github: plugin-filesystem-local
  -
    name:  plugin-filesystem-s3
    github: plugin-filesystem-s3
  -
    name:  plugin-uuid
    github: plugin-uuid